apiVersion: apps/v1
kind: Deployment
metadata:
  name: links
  labels:
    app: links-nginx
  namespace: links
spec:
  replicas: 1
  selector:
    matchLabels:
      app: links-nginx
  template:
    metadata:
      labels:
        app: links-nginx
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsUser: 5000
        runAsGroup: 5000
        fsGroup: 5000
      containers:
      - name: links
        image: ghcr.io/benvon/littlelink_docker:v1.0.0
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: 512M
            cpu: 256m
            ephemeral-storage: 2Gi
          requests:
            memory: 512M
            cpu: 256m
            ephemeral-storage: 2Gi
        securityContext:
          capabilities:
            drop:
              - ALL
          allowPrivilegeEscalation: false
