apiVersion: apps/v1
kind: Deployment
metadata:
  name: links
  labels:
    app: links-nginx
  namespace: links
spec:
  replicas: 1
  selector:
    matchLabels:
      app: links-nginx
  template:
    metadata:
      labels:
        app: links-nginx
    spec:
      containers:
      - name: links
        image: benvon/littlelink:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: 512MiB
            cpu: 256m
          requests:
            memory: 512 MiB
            cpu: 256m