name: Check docker image

on:
  schedule:
    - cron:  '0 4 * * *'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check if update available
        id: check
        uses: lucacome/docker-image-update-checker@v2.0.0
        with:
          base-image: ghcr.io/nginxinc/nginx-unprivileged:1-bookworm
          image: ghcr.io/benvon/littlelink_docker:latest

      - name: Check result
        run: |
            echo "Needs updating: ${{ steps.check.outputs.needs-updating }}"
